using System.Collections.Generic;

namespace Nwazet.Commerce.Services {
    public static class Country {
        private static readonly string[] Countries = {
            "United States",
            "Abu Dhabi (United Arab Emirates)",
            "Admiralty Islands (Papua New Guinea)",
            "Afghanistan",
            "Aitutaki, Cook Islands (New Zealand)",
            "Ajman (United Arab Emirates)",
            "Aland Island (Finland)",
            "Albania",
            "Alberta (Canada)",
            "Alderney (Channel Islands) (Great Britain and Northern Ireland)",
            "Algeria",
            "Alhucemas (Spain)",
            "Alofi Island (New Caledonia)",
            "Andaman Islands (India)",
            "Andorra",
            "Angola",
            "Anguilla",
            "Anjouan (Comoros)",
            "Annobon Island (Equatorial Guinea)",
            "Antigua (Antigua and Barbuda)",
            "Antigua and Barbuda",
            "Argentina",
            "Armenia",
            "Aruba",
            "Ascension",
            "Astypalaia (Greece)",
            "Atafu (Western Samoa)",
            "Atiu, Cook Islands (New Zealand)",
            "Australia",
            "Austria",
            "Avarua (New Zealand)",
            "Azerbaijan",
            "Azores (Portugal)",
            "Bahamas",
            "Bahrain",
            "Balearic Islands (Spain)",
            "Baluchistan (Pakistan)",
            "Bangladesh",
            "Banks Island (Vanuatu)",
            "Barbados",
            "Barbuda (Antigua and Barbuda)",
            "Barthelemy (Guadeloupe)",
            "Belarus",
            "Belgium",
            "Belize",
            "Benin",
            "Bermuda",
            "Bhutan",
            "Bismark Archipelago (Papua New Guinea)",
            "Bolivia",
            "Bonaire (Netherlands Antilles)",
            "Borabora (French Polynesia)",
            "Borneo (Indonesia)",
            "Bosnia-Herzegovina",
            "Botswana",
            "Bougainville (Papua New Guinea)",
            "Bourbon (Reunion)",
            "Brazil",
            "British Columbia (Canada)",
            "British Guiana (Guyana)",
            "British Honduras (Belize)",
            "British Virgin Islands",
            "Brunei Darussalam",
            "Buka (Papua New Guinea)",
            "Bulgaria",
            "Burkina Faso",
            "Burma",
            "Burundi",
            "Caicos Islands (Turks and Caicos Islands)",
            "Cambodia",
            "Cameroon",
            "Canada",
            "Canary Islands (Spain)",
            "Canton Island (Kiribati)",
            "Cape Verde",
            "Cayman Islands",
            "Central African Republic",
            "Ceuta (Spain)",
            "Ceylon (Sri Lanka)",
            "Chad",
            "Chaferinas Islands (Spain)",
            "Chalki (Greece)",
            "Channel Islands (Jersey, Guernsey, Alderney, and Sark) (Great Britain and Northern Ireland)",
            "Chile",
            "China",
            "Christmas Island (Australia)",
            "Christmas Island (Kiribati)",
            "Cocos Island (Australia)",
            "Colombia",
            "Comoros",
            "Congo, Democratic Republic of the",
            "Congo, Republic of the",
            "Cook Islands (New Zealand)",
            "Corisco Island (Equatorial Guinea)",
            "Corsica (France)",
            "Costa Rica",
            "Cote d’Ivoire",
            "Crete (Greece)",
            "Croatia",
            "Cuba",
            "Cumino Island (Malta)",
            "Curacao (Netherlands Antilles)",
            "Cyjrenaica (Libya)",
            "Cyprus",
            "Czech Republic",
            "Dahomey (Benin)",
            "Damao (India)",
            "Danger Islands (New Zealand)",
            "Denmark",
            "Desirade Island (Guadeloupe)",
            "Diu (India)",
            "Djibouti",
            "Dodecanese Islands (Greece)",
            "Doha (Qatar)",
            "Dominica",
            "Dominican Republic",
            "Dubai (United Arab Emirates)",
            "East Timor (Timor-Leste)",
            "Ecuador",
            "Egypt",
            "Eire (Ireland)",
            "El Salvador",
            "Ellice Islands (Tuvalu)",
            "Elobey Islands (Equatorial Guinea)",
            "Enderbury Island (Kiribati)",
            "England (Great Britain and Northern Ireland)",
            "Equatorial Guinea",
            "Eritrea",
            "Estonia",
            "Ethiopia",
            "Fakaofo (Western Samoa)",
            "Falkland Islands",
            "Fanning Island (Kiribati)",
            "Faroe Islands",
            "Fernando Po (Equatorial Guinea)",
            "Fezzan (Libya)",
            "Fiji",
            "Finland",
            "Formosa (Taiwan)",
            "France",
            "French Guiana",
            "French Oceania (French Polynesia)",
            "French Polynesia",
            "French Somaliland (Djibouti)",
            "French Territory of the Afars and Issas (Djibouti)",
            "French West Indies (Guadeloupe)",
            "French West Indies (Martinique)",
            "Friendly Islands (Tonga)",
            "Fujairah (United Arab Emirates)",
            "Futuna (Wallis and Futuna Islands)",
            "Gabon",
            "Gambia",
            "Gambier (French Polynesia)",
            "Georgia, Republic of",
            "Germany",
            "Ghana",
            "Gibraltar",
            "Gilbert Islands (Kiribati)",
            "Goa (India)",
            "Gozo Island (Malta)",
            "Grand Comoro (Comoros)",
            "Great Britain and Northern Ireland",
            "Greece",
            "Greenland",
            "Grenada",
            "Grenadines (Saint Vincent and the Grenadines)",
            "Guadeloupe",
            "Guatemala",
            "Guernsey (Channel Islands) (Great Britain and Northern Ireland)",
            "Guinea",
            "Guinea–Bissau",
            "Guyana",
            "Hainan Island (China)",
            "Haiti",
            "Hashemite Kingdom (Jordan)",
            "Hervey, Cook Islands (New Zealand)",
            "Hivaoa (French Polynesia)",
            "Holland (Netherlands)",
            "Honduras",
            "Hong Kong",
            "Huahine (French Polynesia)",
            "Huan Island (New Caledonia)",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Iran",
            "Iraq",
            "Ireland",
            "Irian Barat (Indonesia)",
            "Isle of Man (Great Britain and Northern Ireland)",
            "Isle of Pines (New Caledonia)",
            "Isle of Pines, West Indies (Cuba)",
            "Israel",
            "Issas (Djibouti)",
            "Italy",
            "Ivory Coast (Cote d’Ivoire)",
            "Jamaica",
            "Japan",
            "Jersey (Channel Islands) (Great Britain and Northern Ireland)",
            "Johore (Malaysia)",
            "Jordan",
            "Kalymnos (Greece)",
            "Kampuchea (Cambodia)",
            "Karpathos (Greece)",
            "Kassos (Greece)",
            "Kastellorizon (Greece)",
            "Kazakhstan",
            "Kedah (Malaysia)",
            "Keeling Islands (Australia)",
            "Kelantan (Malaysia)",
            "Kenya",
            "Kiribati",
            "Korea, Democratic People’s Republic of (North Korea)",
            "Korea, Republic of (South Korea)",
            "Kos (Greece)",
            "Kosovo, Republic of",
            "Kowloon (Hong Kong)",
            "Kuwait",
            "Kyrgyzstan",
            "Labrador (Canada)",
            "Labuan (Malaysia)",
            "Laos",
            "Latvia",
            "Lebanon",
            "Leipsos (Greece)",
            "Leros (Greece)",
            "Les Saints Island (Guadeloupe)",
            "Lesotho",
            "Liberia",
            "Libya",
            "Liechtenstein",
            "Lithuania",
            "Lord Howe Island (Australia)",
            "Loyalty Islands (New Caledonia)",
            "Luxembourg",
            "Macao",
            "Macau (Macao)",
            "Macedonia, Republic of",
            "Madagascar",
            "Madeira Islands (Portugal)",
            "Malacca (Malaysia)",
            "Malagasy Republic (Madagascar)",
            "Malawi",
            "Malaya (Malaysia)",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Manahiki (New Zealand)",
            "Manchuria (China)",
            "Manitoba (Canada)",
            "Manua Islands, American Samoa, Marie Galante (Guadeloupe)",
            "Marquesas Islands (French Polynesia)",
            "Marshall Islands, Republic of the,",
            "Martinique",
            "Mauritania",
            "Mauritius",
            "Mayotte (France)",
            "Melilla (Spain)",
            "Mexico",
            "Micronesia, Federated States of,",
            "Miquelon (Saint Pierre and Miquelon)",
            "Moheli (Comoros)",
            "Moldova",
            "Monaco (France)",
            "Mongolia",
            "Montenegro",
            "Montserrat",
            "Moorea (French Polynesia)",
            "Morocco",
            "Mozambique",
            "Muscat (Oman)",
            "Myanmar (Burma)",
            "Namibia",
            "Nansil Islands (Japan)",
            "Nauru",
            "Negri Sembilan (Malaysia)",
            "Nepal",
            "Netherlands",
            "Netherlands Antilles",
            "Netherlands West Indies (Netherlands Antilles)",
            "Nevis (Saint Christopher and Nevis)",
            "New Britain (Papua New Guinea)",
            "New Brunswick (Canada)",
            "New Caledonia",
            "New Hanover (Papua New Guinea)",
            "New Hebrides (Vanuatu)",
            "New Ireland (Papua New Guinea)",
            "New South Wales (Australia)",
            "New Zealand",
            "Newfoundland (Canada)",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "Nissiros (Greece)",
            "Niue (New Zealand)",
            "Norfolk Island (Australia)",
            "North Borneo (Malaysia)",
            "North Korea (Korea, Democratic People’s Republic of)",
            "Northern Ireland (Great Britain and Northern Ireland)",
            "Northern Mariana Islands, Commonwealth of,",
            "Northwest Territory (Canada)",
            "Norway",
            "Nova Scotia (Canada)",
            "Nukahiva (French Polynesia)",
            "Nukunonu (Western Samoa)",
            "Nyasaland (Malawi)",
            "Ocean Island (Kiribati)",
            "Okinawa (Japan)",
            "Oman",
            "Ontario (Canada)",
            "Pahang (Malaysia)",
            "Pakistan",
            "Palmerston, Avarua (New Zealand)",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Parry, Cook Islands (New Zealand)",
            "Patmos (Greece)",
            "Pemba (Tanzania)",
            "Penang (Malaysia)",
            "Penghu Islands (Taiwan)",
            "Penon de Velez de la Gomera (Spain)",
            "Penrhyn, Tongareva (New Zealand)",
            "Perak (Malaysia)",
            "Perlis (Malaysia)",
            "Persia (Iran)",
            "Peru",
            "Pescadores Islands (Taiwan)",
            "Petite Terre (Guadeloupe)",
            "Philippines",
            "Pitcairn Island",
            "Poland",
            "Portugal",
            "Prince Edward Island (Canada)",
            "Province Wellesley (Malaysia)",
            "Pukapuka (New Zealand)",
            "Qatar",
            "Quebec (Canada)",
            "Queensland (Australia)",
            "Quemoy (Taiwan)",
            "Raiatea (French Polynesia)",
            "Rakaanga (New Zealand)",
            "Rapa (French Polynesia)",
            "Rarotonga, Cook Islands (New Zealand)",
            "Ras al Kaimah (United Arab Emirates)",
            "Redonda (Antigua and Barbuda)",
            "Reunion",
            "Rhodesia (Zimbabwe)",
            "Rio Muni (Equatorial Guinea)",
            "Rodos (Greece)",
            "Rodrigues (Mauritius)",
            "Romania",
            "Rota, Northern Mariana Islands,",
            "Russia",
            "Rwanda",
            "Saba (Netherlands Antilles)",
            "Sabah (Malaysia)",
            "Saint Barthelemy (Guadeloupe)",
            "Saint Bartholomew (Guadeloupe)",
            "Saint Christopher and Nevis",
            "Saint Eustatius (Netherlands Antilles)",
            "Saint Helena",
            "Saint John, US Virgin Islands,",
            "Saint Kitts (Saint Christopher and Nevis)",
            "Saint Lucia",
            "Saint Maarten (Dutch) (Netherlands Antilles)",
            "Saint Martin (French) (Guadeloupe)",
            "Saint Pierre and Miquelon",
            "Saint Thomas, US Virgin Islands,",
            "Saint Vincent and the Grenadines",
            "Sainte Marie de Madagascar (Madagascar)",
            "Saipan, Northern Mariana Islands,",
            "Salvador (El Salvador)",
            "San Marino",
            "Santa Cruz Islands (Solomon Island)",
            "Sao Tome and Principe",
            "Sarawak (Malaysia)",
            "Sark (Channel Islands) (Great Britain and Northern Ireland)",
            "Saskatchewan (Canada)",
            "Saudi Arabia",
            "Savage Island, Niue (New Zealand)",
            "Savaii Island (Western Samoa)",
            "Scotland (Great Britain and Northern Ireland)",
            "Selangor (Malaysia)",
            "Senegal",
            "Serbia, Republic of",
            "Seychelles",
            "Sharja (United Arab Emirates)",
            "Shikoku (Japan)",
            "Siam (Thailand)",
            "Sierra Leone",
            "Sikkim (India)",
            "Singapore",
            "Slovak Republic (Slovakia)",
            "Slovenia",
            "Society Islands (French Polynesia)",
            "Solomon Islands",
            "Somali Democratic Republic (Somalia)",
            "Somalia",
            "Somaliland (Somalia)",
            "South Africa",
            "South Australia (Australia)",
            "South Georgia (Falkland Islands)",
            "South Korea (Korea, Republic of)",
            "South–West Africa (Namibia)",
            "Spain",
            "Spitzbergen (Norway)",
            "Sri Lanka",
            "Sudan",
            "Suriname",
            "Suwarrow Islands (New Zealand)",
            "Swain’s Island, American Samoa,",
            "Swan Islands (Honduras)",
            "Swaziland",
            "Sweden",
            "Switzerland",
            "Symi (Greece)",
            "Syrian Arab Republic (Syria)",
            "Tahaa (French Polynesia)",
            "Tahiti (French Polynesia)",
            "Taiwan",
            "Tajikistan",
            "Tanzania",
            "Tasmania (Australia)",
            "Tchad (Chad)",
            "Thailand",
            "Thursday Island (Australia)",
            "Tibet (China)",
            "Tilos (Greece)",
            "Timor (Indonesia)",
            "Timor-Leste, Democratic Republic of",
            "Tinian, Northern Mariana Islands,",
            "Tobago (Trinidad and Tobago)",
            "Togo",
            "Tokelau (Union Group) (Western Samoa)",
            "Tonga",
            "Tongareva (New Zealand)",
            "Tori Shima (Japan)",
            "Torres Island (Vanuatu)",
            "Trans-Jordan, Hashemite Kingdom (Jordan)",
            "Transkei (South Africa)",
            "Trengganu (Malaysia)",
            "Trinidad and Tobago",
            "Tripolitania (Libya)",
            "Tristan da Cunha",
            "Trucial States (United Arab Emirates)",
            "Tuamotou (French Polynesia)",
            "Tubuai (French Polynesia)",
            "Tunisia",
            "Turkey",
            "Turkmenistan",
            "Turks and Caicos Islands",
            "Tuvalu",
            "Uganda",
            "Ukraine",
            "Umm al Quaiwain (United Arab Emirates)",
            "Umm Said (Qatar)",
            "Union Group (Western Samoa)",
            "United Arab Emirates",
            "United Kingdom (Great Britain and Northern Ireland)",
            "Upolu Island (Western Samoa)",
            "Uruguay",
            "Uzbekistan",
            "Vanuatu",
            "Vatican City",
            "Venezuela",
            "Victoria (Australia)",
            "Vietnam",
            "Virgin Islands (British)",
            "Wales (Great Britain and Northern Ireland)",
            "Wallis and Futuna Islands",
            "Wellesley, Province (Malaysia)",
            "West New Guinea (Indonesia)",
            "Western Australia (Australia)",
            "Western Samoa",
            "Yemen",
            "Yukon Territory (Canada)",
            "Zafarani Islands (Spain)",
            "Zambia",
            "Zanzibar (Tanzania)",
            "Zimbabwe"
        };

        public static IEnumerable<string> List { get { return Countries; } }
        public static string UnitedStates = Countries[0];
    }
}
